name: dart_basic_class_exercises
description: Basic Dart class exercises and operator overloading examples
version: 1.0.0

environment:
  sdk: '^3.0.0'

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.24.0